services:
  - type: web
    name: hotelbooking-v2-api
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/HotelBooking.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
